name: Compile and release

on:
  push:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v2

      - name: Set environment variables
        run: echo SCRIPTS_PATH=$(pwd) >> $GITHUB_ENV
      - name: Setup SourcePawn Compiler ${{ matrix.SM_VERSION }}
        id: setup_sp
        uses: rumblefrog/setup-sp@master
        with:
          version: "1.11.x"
          version-file: ./scripting/smart_fastdownloads.sp
      
      - name: Download dependencies
        run: |
          mkdir scripting/include
          cd scripting/include
          
          wget "https://raw.githubusercontent.com/accelerator74/SxGeo/master/Release/sxgeo.inc"
          
          cd ../..

      - name: Compile plugins
        run: |
          mkdir plugins
          cd scripting
          spcomp -E -w234 -O2 -v2 -i $includePath -i"include" -o"../plugins/smart_fastdownloads.smx" smart_fastdownloads.sp
          echo "===OUT FILES==="
          cd ../plugins
          ls
          echo "===VERSION==="
          echo ${{ steps.setup_sp.outputs.plugin-version }}
        working-directory: ${{ env.SCRIPTS_PATH }}

      - name: Changelog
        id: changelog
        uses: mindsers/changelog-reader-action@v2.0.0

      - name: Install zip
        uses: montudor/action-zip@v1

      - name: Zip output
        run: |
          cd plugins
          zip -qq -r smart_fastdownloads-${{ steps.setup_sp.outputs.plugin-version }}.zip smart_fastdownloads.smx
        working-directory: ${{ env.SCRIPTS_PATH }}

      - name: Create Release
        uses: ncipollo/release-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: v${{ steps.setup_sp.outputs.plugin-version }}
          artifacts: "./plugins/smart_fastdownloads-${{ steps.setup_sp.outputs.plugin-version }}.zip"
          body: ${{ steps.changelog.outputs.changes }}
          draft: false
          allowUpdates: true
          prerelease: false
          replacesArtifacts: true
